typography_spectrum: 0.07250267
color:
  saturation: 0.7313807
  brandStrength: 0.4446396
  rhythmicContrast: 0.8199917
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.2383864
layout_spectrum: 0.6016742
name: Nullpothesis
navigation:
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/andrewpeynado'
    type: external
  - name: About Me
    id: 0f1699f8-758d-417f-881d-154183401912
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: tech x product x data
description: Question The Status Quo
